[package]
name = "nd_compression"
version = "0.1.0"
edition = "2024"

[dependencies]
bitvec = "1.0.1"
itertools = "0.14.0"

[[bench]]
name = "main"
harness = false

[dev-dependencies]
criterion = "0.5.1"
rand = "0.9.0"
