[package]
name = "nd_compression"
version = "0.1.0"
edition = "2024"

[dependencies]
itertools = "0.14.0"
prime_factorization = "1.0.5"

[[bench]]
name = "main"
harness = false

[dev-dependencies]
criterion = "0.5.1"
